language: node_js
script:
  - npm test
deploy:
  provider: script
  script: NETLIFY_SITE_ID=$NETLIFY_SITE_ID NETLIFY_ACCESS_TOKEN=$NETLIFY_ACCESS_TOKEN node deploy.js
  skip_cleanup: true
  on:
    branch: master
